export const services = [
    "All",
    "Orthopaedic",
    "Laparoscopic",
    "Urology",
    "ENT",
    "Gynacology",
    "Ophthamology",
    "Pediatric",
    "Anaesthesia",
    "Radio Diagnosis",
    "Cardiology",
    "Obstetrics",
    "Dermotology",
    "Pulmonology",
    "Psychiatry",
    "Cataract Surgery",
    "LASIK Eye Surgery",
    "Haemogram",
    "Hemoglobin Test",
    "Ferritin Test",
    "Coronary Angioplasty",
    "Urinalysis",
    "Endoscopy",
    "Naturopathy",
    "Acupuncture",
    "Physiotherapy"
]

export const bloodGrp = ["All","A+","A-","B+","B-","AB+","AB-","O+","O-"]